### ISSUE TITLE
error when populate using the example

### ISSUE THREAD

**Issue by josehu-t** [postgrespro/vops#22]
postgres=# create table vops_lineitem(  
postgres(#    l_shipdate vops_date not null,  
postgres(#    l_quantity vops_float4 not null,  
postgres(#    l_extendedprice vops_float4 not null,  
postgres(#    l_discount vops_float4 not null,  
postgres(#    l_tax vops_float4 not null,  
postgres(#    l_returnflag vops_char not null,  
postgres(#    l_linestatus vops_char not null  
postgres(# );  
CREATE TABLE
postgres=# select populate(destination := 'vops_lineitem'::regclass, source := 'lineitem'::regclass);  
2021-09-01 15:04:54.658 CST [26612] ERROR:  Incompatible type of attribute 6: "char" vs. character
2021-09-01 15:04:54.658 CST [26612] STATEMENT:  select populate(destination := 'vops_lineitem'::regclass, source := 'lineitem'::regclass);
ERROR:  Incompatible type of attribute 6: "char" vs. character

**Comment by josehu-t** [comment]
remove two char column to avoid error

**Comment by knizhnik** [comment]
Sorry, are you using master branch?
And did you use definition of lineitem table from the tpch.sql example or you have have created it yourself.
Please notice that type of l_returnflag and l_linestatus  columns should be `"char"`, not `char(1)`
In Postgres `"char"` and `char` are different types. First one represent single byte integer.

**Comment by josehu-t** [comment]
get it! thanks a lot.

> Sorry, are you using master branch?
> And did you use definition of lineitem table from the tpch.sql example or you have have created it yourself.
> Please notice that type of l_returnflag and l_linestatus columns should be `"char"`, not `char(1)`
> In Postgres `"char"` and `char` are different types. First one represent single byte integer.
