### ISSUE TITLE
Are there any blogs?

### ISSUE THREAD

**Issue by suuuch** [postgrespro/vops#7]
I am first time to use vops,but I can not find how to install vops?
Are there any blogs?

**Comment by knizhnik** [comment]
Sorry, there are no blogs about VOPS now.
You can install VOPS as any other Postgres extension. First of all you need to build it. Please read Postgres manual about building and installing extensions:
https://www.postgresql.org/docs/current/static/extend-pgxs.html
Once you build vops extension, you should add it to shared_preload_libraries list in postgresql configuration file, restart postgres and do "create extension vops".

**Comment by suuuch** [comment]
@knizhnik Thank you.
